MOCK_POSITIONS = [
    {
        "id": "p1",
        "symbol": "NHPC",
        "exchange": "NSE",
        "qty": 10,
        "entry_price": 82.50,
        "ltp": 86.20,
        "pnl": 37.00,
        "pnl_pct": 4.48,
        "product": "MIS",
        "mode": "paper",
        "entry_time": "09:24:12",
        "target": 88.00,
        "stoploss": 80.50,
        "status": "open",
    },
    {
        "id": "p2",
        "symbol": "IRCTC",
        "exchange": "NSE",
        "qty": 3,
        "entry_price": 748.00,
        "ltp": 741.30,
        "pnl": -20.10,
        "pnl_pct": -0.90,
        "product": "MIS",
        "mode": "paper",
        "entry_time": "10:11:46",
        "target": 760.00,
        "stoploss": 738.00,
        "status": "open",
    },
]

MOCK_TRADES = [
    {
        "id": "9f1c2a7b",
        "date": "2026-04-16",
        "symbol": "SAIL",
        "action": "BUY",
        "qty": 20,
        "entry_price": 128.50,
        "exit_price": 132.10,
        "pnl": 72.00,
        "pnl_pct": 2.80,
        "status": "closed",
        "mode": "paper",
        "signal_reason": "RSI rebound with bullish MACD crossover",
        "duration": "42m",
    },
    {
        "id": "4b7d8e1c",
        "date": "2026-04-16",
        "symbol": "TCS",
        "action": "BUY",
        "qty": 1,
        "entry_price": 4025.00,
        "exit_price": 3982.00,
        "pnl": -43.00,
        "pnl_pct": -1.07,
        "status": "closed",
        "mode": "paper",
        "signal_reason": "Opening range breakout failed to sustain",
        "duration": "27m",
    },
    {
        "id": "c3a91d5e",
        "date": "2026-04-15",
        "symbol": "NHPC",
        "action": "BUY",
        "qty": 25,
        "entry_price": 81.40,
        "exit_price": 84.20,
        "pnl": 70.00,
        "pnl_pct": 3.44,
        "status": "closed",
        "mode": "paper",
        "signal_reason": "Support retest held with rising volume",
        "duration": "1h 08m",
    },
    {
        "id": "1e6f4b9a",
        "date": "2026-04-15",
        "symbol": "IDEA",
        "action": "BUY",
        "qty": 100,
        "entry_price": 14.90,
        "exit_price": 14.20,
        "pnl": -70.00,
        "pnl_pct": -4.70,
        "status": "closed",
        "mode": "paper",
        "signal_reason": "Momentum faded after weak follow-through",
        "duration": "19m",
    },
    {
        "id": "7a2c5d8f",
        "date": "2026-04-14",
        "symbol": "RELIANCE",
        "action": "BUY",
        "qty": 2,
        "entry_price": 2892.00,
        "exit_price": 2958.50,
        "pnl": 133.00,
        "pnl_pct": 2.30,
        "status": "closed",
        "mode": "paper",
        "signal_reason": "Breakout above intraday consolidation",
        "duration": "53m",
    },
]

MOCK_SIGNALS = [
    {
        "id": "sig-001",
        "timestamp": "09:18:04",
        "symbol": "IRCTC",
        "exchange": "NSE",
        "action": "BUY",
        "entry_price": 742.00,
        "target": 756.00,
        "stoploss": 735.00,
        "qty": 2,
        "rsi": 38,
        "macd_state": "bullish_cross",
        "confidence": 78,
        "risk_status": "approved",
        "executed": True,
        "mode": "paper",
    },
    {
        "id": "sig-002",
        "timestamp": "10:57:31",
        "symbol": "SAIL",
        "exchange": "NSE",
        "action": "BUY",
        "entry_price": 127.80,
        "target": 132.50,
        "stoploss": 125.00,
        "qty": 15,
        "rsi": 41,
        "macd_state": "bullish_cross",
        "confidence": 74,
        "risk_status": "approved",
        "executed": False,
        "mode": "paper",
    },
    {
        "id": "sig-003",
        "timestamp": "11:23:49",
        "symbol": "IDEA",
        "exchange": "NSE",
        "action": "BUY",
        "entry_price": 14.80,
        "target": 15.40,
        "stoploss": 14.60,
        "qty": 100,
        "rsi": 67,
        "macd_state": "bearish_cross",
        "confidence": 52,
        "risk_status": "rejected",
        "executed": False,
        "mode": "paper",
        "reject_reason": "Confidence below threshold and bearish MACD crossover",
    },
]

MOCK_AGENT_LOGS = [
    {
        "time": "09:14:58",
        "agent": "market_scanner",
        "level": "info",
        "msg": "Scheduled market scan initialized for paper session",
    },
    {
        "time": "09:15:02",
        "agent": "market_scanner",
        "level": "success",
        "msg": "Watchlist scan completed with 3 candidate setups",
    },
    {
        "time": "09:15:06",
        "agent": "risk_gatekeeper",
        "level": "info",
        "msg": "Evaluating IRCTC buy signal against capital and RR constraints",
    },
    {
        "time": "09:15:08",
        "agent": "risk_gatekeeper",
        "level": "success",
        "msg": "IRCTC signal approved with RR 1.87 and confidence 78",
    },
    {
        "time": "09:16:11",
        "agent": "execution",
        "level": "warning",
        "msg": "Execution agent is stopped; queued paper order was not sent",
    },
    {
        "time": "10:02:44",
        "agent": "market_scanner",
        "level": "warning",
        "msg": "No valid setups found in RELIANCE after RSI filter",
    },
    {
        "time": "10:03:12",
        "agent": "risk_gatekeeper",
        "level": "error",
        "msg": "Rejected IDEA signal due to low confidence and bearish MACD state",
    },
    {
        "time": "11:00:00",
        "agent": "market_scanner",
        "level": "info",
        "msg": "Manual rescan requested from dashboard",
    },
    {
        "time": "11:00:04",
        "agent": "risk_gatekeeper",
        "level": "success",
        "msg": "SAIL signal cleared for paper execution",
    },
    {
        "time": "11:00:10",
        "agent": "execution",
        "level": "error",
        "msg": "Execution agent unavailable while attempting to process SAIL order",
    },
]

MOCK_AGENTS = {
    "market_scanner": {
        "status": "stopped",
        "last_run": "2026-04-16T11:00:00Z",
        "mode": "paper",
    },
    "risk_gatekeeper": {
        "status": "running",
        "last_run": "2026-04-16T11:00:04Z",
        "mode": "paper",
    },
    "execution": {
        "status": "stopped",
        "last_run": None,
        "mode": "paper",
    },
}

MOCK_CONFIG = {
    "capital_limit": 5000,
    "max_trade_value": 2000,
    "max_loss_per_trade": 300,
    "min_rr_ratio": 1.5,
    "scan_times": ["09:15", "11:00", "13:30"],
    "watchlist": [
        "NHPC",
        "SAIL",
        "NBCC",
        "IRFC",
        "HUDCO",
        "RVNL",
        "BHEL",
        "NTPC",
        "POWERGRID",
        "RECLTD",
        "PFC",
        "SJVN",
        "NMDC",
        "NATIONALUM",
        "MRPL",
        "HINDPETRO",
        "BANKBARODA",
        "CANBK",
        "IDEA",
        "SUZLON",
    ],
    "mode": "paper",
    "rsi_oversold": 35,
    "rsi_overbought": 65,
    "confidence_threshold": 70,
    "default_product_type": "MIS",
    "auto_squareoff_time": "15:15",
}

MOCK_CAPITAL = {
    "total": 5000,
    "available": 3241.50,
    "deployed": 1758.50,
    "today_pnl": 342.50,
    "today_pnl_pct": 6.85,
    "open_positions": 2,
    "trades_today": 3,
}
