"""initial schema

Revision ID: a3fe543fdb6f
Revises: 
Create Date: 2026-04-16 18:28:32.003771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fe543fdb6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('msg', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capital_limit', sa.Float(), nullable=True),
    sa.Column('max_trade_value', sa.Float(), nullable=True),
    sa.Column('max_loss_per_trade', sa.Float(), nullable=True),
    sa.Column('min_rr_ratio', sa.Float(), nullable=True),
    sa.Column('scan_times', sa.String(length=200), nullable=True),
    sa.Column('watchlist', sa.String(length=500), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('rsi_oversold', sa.Float(), nullable=True),
    sa.Column('rsi_overbought', sa.Float(), nullable=True),
    sa.Column('confidence_threshold', sa.Integer(), nullable=True),
    sa.Column('default_product_type', sa.String(length=10), nullable=True),
    sa.Column('auto_squareoff_time', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('stoploss', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd_state', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('risk_status', sa.String(length=20), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('product', sa.String(length=10), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('signal_reason', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('entry_time', sa.String(length=30), nullable=True),
    sa.Column('exit_time', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('config')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
